import type { Metadata } from "next";
import { isAddress } from "viem";
import { getCreation } from "@/lib/tokenFeed";
import TokenPageClient from "./TokenPageClient";

/**
 * Server wrapper: the page UI is a client component (`TokenPageClient`), but the
 * route is a server component so it can export `generateMetadata` for rich social
 * previews. The OG/Twitter card image is generated by `opengraph-image.tsx`.
 */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ address: string }>;
}): Promise<Metadata> {
  const { address } = await params;

  // Pull the launch's name/symbol from the cached feed (best-effort; a cold cache
  // or an unknown address just yields generic metadata rather than failing).
  const creation = isAddress(address)
    ? await getCreation(address).catch(() => undefined)
    : undefined;
  const name = creation?.name?.trim();
  const symbol = creation?.symbol?.trim();

  const title = name
    ? `${name}${symbol ? ` ($${symbol})` : ""} · PotatoPad`
    : "Token · PotatoPad";
  const description = name
    ? `Trade ${name}${symbol ? ` ($${symbol})` : ""} on PotatoPad — launched direct-to-Uniswap V3, single-sided liquidity locked forever.`
    : "A token launched on PotatoPad — direct-to-Uniswap V3, with single-sided liquidity locked forever.";

  return {
    title,
    description,
    openGraph: { title, description, type: "website" },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default function TokenPage() {
  return <TokenPageClient />;
}
